### ISSUE TITLE
Add Multi-look function

### ISSUE THREAD

**Issue by rogerkuou** [MotionbyLearning/sarxarray#29]
An prototype multilook function can be found [two archived notebooks](https://github.com/MotionbyLearning/sarxarray/tree/main/examples/archive). We need to add them as delayed functions in [`sarxarray.stack`](https://github.com/MotionbyLearning/sarxarray/blob/main/sarxarray/stack.py).

In Zoe's example, she uses `view_as_windows` from `skimage` as multiplook window. But maybe `rolling` from dask can be more parallelizable?

Example SAR stack can be downloaded [here](https://figshare.com/articles/dataset/nl_amsterdam_s1_asc_t088_zip/23268221).

**Comment by SarahAlidoost** [comment]
I found that  `view_as_windows` from skimage implements a Rolling window (overlapping), see its [doc](https://scikit-image.org/docs/stable/api/skimage.util.html#skimage.util.view_as_windows). 
There is[ this xarray tutorial](https://tutorial.xarray.dev/fundamentals/03.3_windowed.html) that shows two methods of Windowed Computations: 1. [rolling](https://docs.xarray.dev/en/stable/user-guide/computation.html#rolling-window-operations) - Sliding windows of fixed length., 2. [coarsen](https://docs.xarray.dev/en/stable/user-guide/computation.html#coarsen-large-arrays) - block windows of fixed length. In both cases, it is possible to have different sizes for different dimensions.
